[opener]
edit = [
	{ run = '$EDITOR "$@"', block = true, for = "unix" },
]
pdf = [
    { run = 'zathura "$@"', orphan = true, for = "unix" },
]

[open]
rules = [
    { mime = "text/*", use = "edit" },
    { mime = "application/pdf", use = "pdf" },
]
