[shell]
font_family = "SourceCodePro,NotoSansCJK"

[theme]
builtin = "Gruvbox"

[wallpaper]
directory = "~/media/wallpaper/3840x2160"

[wallpaper.automation]
enabled = true

[bar.default]
position = "bottom"
auto_hide = true
reserve_space = false
center = ["clock", "pomodoro-timer"]

[idle.behavior.screen-off]
timeout = 300
action = "screen_off"
enabled = true

[plugins]
enabled = ["thepunkoff/pomodoro"]

[widget.pomodoro-timer]
type = "thepunkoff/pomodoro:widget"
