[shell]
font_family = "SourceCodePro,NotoSansCJK"

[theme]
builtin = "Gruvbox"

[wallpaper]
directory = "~/media/wallpaper/3840x2160"

[bar.default]
position = "bottom"
auto_hide = true
smart_auto_hide = true
show_on_workspace_switch = true
reserve_space = false

[idle.behavior.screen-off]
timeout = 300
action = "screen_off"
enabled = true
