title   Arch Linux
linux   /vmlinuz-linux
initrd  /amd-ucode.img
initrd  /intel-ucode.img
initrd  /initramfs-linux.img
options root=UUID=$$ROOTFS_PARTITION_UUID$$ rw
options quiet vt.global_cursor_default=0 loglevel=2 rd.systemd.show_status=false rd.udev.log-priority=3
options pcie_aspm=off usbhid.quirks=0x0c45:0xfefe:0x400
